server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1068470782537-b7mcaif0ibcjbf7ufpfqp358lab9rm2n.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

tms:
  service:
    url: http://localhost:8080  # URL where the TMS service is hosted

jwt:
  secret: avo39dCJsnW1/1FktGOqtFsVjVDvKd2RiTmjZoI7LLWE4nzurzSG7D9+1zeWMMjNcyljW94TdiDTb0QNzvs3gA== # YOUR_JWT_SECRET_KEY
  expiration: 3600000  # JWT expiration time in milliseconds (1 hour)
